default_platform(:ios)

platform :ios do
  desc "Build en upload naar TestFlight"
  lane :beta do
    setup_ci if ENV['CI']

    match(
      type: "appstore",
      readonly: is_ci,
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
    )

    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
    )

    upload_to_testflight(
      api_key: {
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_PRIVATE_KEY"],
        is_key_content_base64: true,
        duration: 1200,
        in_house: false,
      },
      skip_waiting_for_build_processing: true,
    )
  end
end
