name: claeren_policy_app
description: Claeren mobiele polissen-app – schadeverzekeringen voor particulieren en zakelijke relaties.
version: 1.0.0+8

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
